### ISSUE TITLE
Repair Delete Mezcal Button on Edit-Mezcal/id

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#24]
Details: Currently the button for deleting mezcals on the edit mezcal page is not working there is already a handler for it in the edit mezcal js but for some reason when clicked it is only registering the submit button and not the delete button. Could use extra eyes on this as soon as possible. 

Potential Error: Please only edit handlebars files in the views and the js files in the Public folder. Either edit-mezcal.handlebars or editMezcal.js should be all thats needed to fix this issue.  Please don't push any changed to homeRoutes, controllers, etc for this request.

**Comment by NickSweet1** [comment]
issue resolved
