### ISSUE TITLE
Create functioning search bar script 

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#27]
Details: We currently do not have a working search function. it is not a requirement but it would be advantageous for users to be able to search for a brand or agave or flavor and be given all the mezcals that have matching text or abv.  This may take multiple contributors as it will need a JavaScript page and specific routes.  We should be able to utilize our edit mezcal handlebar and use a "#each" handlebar expression to render a unique card for all the mezcals that fit the searched input parameters

**Comment by NickSweet1** [comment]
OPTIONAL

**Comment by NickSweet1** [comment]
issue resolved. Good work team
