### ISSUE TITLE
Test All Functions and Routes

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#28]
Details: Once we have all elements running we need to test each individual function of our page so that we can make sure everything is working together correctly.  All routes have currently be tested but we should run over all of them again in case changes have caused any disruptions.

Potential Error: Insomnia will be the best bet for checking on both of these issues and will probably be the quickest method

**Comment by technerdpablo** [comment]
Thoroughly went through code and cleaned up all unnecessary comments and all unusable routes. I then ran all routes through insomnia and verified that they were working.
