### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#29]
Details: Our page currently has no Heroku deployment.  This is something we should tackle immediately so we are prepared for any issues that may come up we should try to get this deployed as soon as possible, as we can always redeploy later with changes.

Potential Error: an unforeseen amount of errors can come up with Heroku and it will be best to do this in class and utilize the TA's and Gurmeet to help us incase of any problems

**Comment by NickSweet1** [comment]
heroku app deployed
