### ISSUE TITLE
List of mezcals with conflicting brand/name

### ISSUE THREAD

**Issue by NickSweet1** [JoshuaVaneps/Mezcal-Book#38]
This is a list of all seeded mezcals with a brand that doesn't necessarily have a unique name. More research may need to be done to get a specific name for the mezcals. Currently, the name is just the agave type.
Bruxo #2,
La Higuera,
Mina Real,
Montelobos,
Ojo de Tigre,
Peloton,
Por Siempre.
It may be that the agave type (ex. Espadin, Barril, etc) is the best way to have these seeded. If so, no change needs to be made.

**Comment by JoshuaVaneps** [comment]
woking on this now and changing the name from the brand to the agave

**Comment by JoshuaVaneps** [comment]
was able to finish all of these
