### ISSUE TITLE
Create Cocktail Model

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#41]
# Details: 
we need a model almost for Cocktails it can be similar to the mezcal model but shouldn't be identical please utilize a name, spirit and ingredients category. we may at some point need a common allergen category also but in most cases please coordinate with nick on this model as he will have the most relevant knowledge base for this assignment

# Possible Errors:  
Please only edit the models folder while working on this problem and please utilize a designated branch for this specific issue.  Make sure to comment below if you are currently working on it or plan to take on this issue.  Doing so will enable us to avoid any conflicts or wasted time, thank you.

# Example:

![Screenshot 2023-08-11 111913](https://github.com/JoshuaVaneps/Mezcal-Book/assets/111782130/5858cdad-79d4-4e69-8c7e-fbf4c7a7be16)

**Comment by NickSweet1** [comment]
done
