### ISSUE TITLE
Rip Photos and Remove Background

### ISSUE THREAD

**Issue by JoshuaVaneps** [JoshuaVaneps/Mezcal-Book#46]
# Details: 
Utilize the [Google Doc](https://docs.google.com/document/d/151lFLZOfK-jCT36KjOs3a6bV2P5oOYvpdmVGOM7NBYw/edit?usp=sharing) to gather all of the tequila photos.  You should be able to rip all photos from the dock using the method shown in the video below.  The tequila bottles should start from Altos . once you have those go to [remove.bg](https://www.remove.bg/) and remove the backgrounds once you have them add them to a [Google Photos Album](https://www.google.com/photos/about/) and utilize the URL to populate the tequila seeds with image URLs.

# Possible Errors: 
one error we often came across was to make sure you open a new tab of the phot before clicking copy image address that is the correct url needed to see the image in our site.  Also make sure your checking every 3 seeds added to make sure the images are actually being rendered.  The tequila handlebars will need to be created for you to easily check this.

# Instruction Video: 

[video](https://drive.google.com/file/d/1llQ8vg0DhFRJtxENEkitugTkP5OAeQ5_/view)

**Comment by NickSweet1** [comment]
harrison completed on 8/12.
